### ISSUE TITLE
Overlay threat model assumes honest perturbers

### ISSUE THREAD

**Issue by mzweilin** [IntelLabs/MART#22]
https://github.com/IntelLabs/MART/blob/6184ca764c871cc098a4e822e520f476e556a971/mart/attack/threat_model.py#L60

It should be better to return `input * (1 - mask) + perturbation * mask`, in case the perturbation is not constrained to the masked region.

**Comment by dxoigmn** [comment]
This is also true of `AdditiveThreatModel`:
https://github.com/IntelLabs/MART/blob/6184ca764c871cc098a4e822e520f476e556a971/mart/attack/threat_model.py#L46

There ought to be some limit on the perturbation here that is specified independently of what the adversary does.

**Comment by mzweilin** [comment]
We may want to rename `Overlay` as `MaskOverlay` to remind us that there must be a mask.
