### ISSUE TITLE
Circular import issue with Adversary reference

### ISSUE THREAD

**Issue by lumurillo** [IntelLabs/MART#38]
When trying to reference the `Adversary` type in the `Callback` interface it provokes a import circular issue.

**Comment by dxoigmn** [comment]
Can you document the issue better? That will make it easier to review the associated PR.

**Comment by lumurillo** [comment]
The problem is that since `Adversary` make use of the `Callback` class, and the `Callback` base class also make use of the `Adversary` class; when adding the typing hints this is provoking a circular import issue.

**Comment by dxoigmn** [comment]
Do you have a PR that exhibits this issue? Easier for me to read code and make suggestions than interpret english descriptions of code.

**Comment by lumurillo** [comment]
Last commit in PR #29 solve this.
