### ISSUE TITLE
Attack parameters are wrongly saved to model checkpoint

### ISSUE THREAD

**Issue by mzweilin** [IntelLabs/MART#40]
https://github.com/IntelLabs/MART/blob/2cb258dec4abd52e2468fc8445ab9464d02c9e9c/mart/attack/adversary.py#L94

We used to do `self.perturber = [perturber]` and reference it as `self.perturber[0]`. Do you know why it was changed? @dxoigmn

**Comment by dxoigmn** [comment]
There was no comment as to why that particular line was necessary, so I removed it because none of the tests failed.

**Comment by mzweilin** [comment]
I wonder if PyTorch supports a more elegant way of excluding certain members from `module.parameters()`.
